# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WEBAPP_NAME: AppWeb-DevOps  # Azure Web App Name
  WEBAPP_PACKAGE_PATH: './Adelys/Adelys/Adelys.csproj'      # Project Path Location default to root(.)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        # Runs a single command using the runners shell
      - name: Install dependencies
        run: dotnet restore ./Adelys/Adelys.sln

      - name: Build
        run: dotnet build ./Adelys/Adelys/Adelys.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Adelys/AdelysTests/AdelysTests.csproj --no-restore --verbosity normal


      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
            app-name: ${{ env.WEBAPP_NAME }} 
            publish-profile: ${{ secrets.AZURE_WEBAPP }}
            package: /site/wwwroot/Adelys/Adelys/bin/Release/net6.0/Adelys.dll